### ISSUE TITLE
Reinstall Problem

### ISSUE THREAD

**Issue by fongtech** [4teamwork/ftw.theming#72]
After installing plonetheme.blueberry.standard (1.8.5) together with ftw.theming (base) (1.9.0), all is fine with the new theme.

But if you reinstall ftw.theming (base) under portal_quickinstaller, the theme will break.. site will go back to Sunburst theme and impossible to recover plone instance to the new theme.

Using Plone 4.3.12

Earlier I was trying to upgrade ftw.theming 1.7.1 to 1.9.0

**Comment by raphael-s** [comment]
I just released version `1.10.0` which should fix your problem :)
